services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"   # Portainer web UI
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Portainer to manage your host/Swarm
    networks:
      - backend-nw

volumes:
  portainer_data:

networks:
  backend-nw:
    external: true
