version: "3.9"

services:
  port-manager:
    image: ghcr.io/port-labs/port-manager:latest   # hypothetical manager image
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: "production"
    networks:
      - backend-nw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # gives access to Docker
      - port-manager-data:/app/data
    ports:
      - "9000:9000"   # Port.io web UI

volumes:
  port-manager-data:

networks:
  backend-nw:
    external: true
