services:
  rancher:
    image: rancher/rancher:v2.10.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8181:80"    # HTTP
      - "8443:443"   # HTTPS
    volumes:
      - rancher-data:/var/lib/rancher
    networks:
      - rancher-network

volumes:
  rancher-data:

networks:
  rancher-network:
    driver: overlay
