services:
  port-manager:
    image: ghcr.io/getport-io/manager:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
    networks:
      - backend-nw
    volumes:
      - port-data:/app/data
    ports:
      - "3000:3000"  # access via browser

volumes:
  port-data:

networks:
  backend-nw:
    external: true
