version: '3.8' # Added back for maximum Swarm stability/feature parsing

services:
  rancher:
    image: rancher/rancher:v2.10.1
    privileged: true 
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any 
        delay: 5s 
        max_attempts: 3
        window: 120s

    ports:
      - target: 80
        published: 8181
        protocol: tcp
        mode: ingress
      - target: 443
        published: 8443
        protocol: tcp
        mode: ingress
        
    volumes:
      # This name (rancher-vol) MUST match the name in the 'volumes' section below
      - rancher-vol:/var/lib/rancher 

    networks:
      - rancher-nw

volumes:
  rancher-vol: # <--- FIXED: Must match the name used in the 'volumes' block of the service
    external: true
    
networks:
  rancher-nw:
    external: true
