services:
  getport:
    image: ghcr.io/getport-io/manager:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SERVER_PORT: 3000
      NODE_ENV: production
    volumes:
      - getport-data:/app/data
    networks:
      - backend-nw

  getport-agent:
    image: ghcr.io/getport-io/agent:latest
    deploy:
      mode: global   # One agent per Swarm node
      restart_policy:
        condition: on-failure
    environment:
      SERVER_URL: "http://getport:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend-nw

volumes:
  getport-data:

networks:
  backend-nw:
    external: true
